2018-10-15 15:35:32,224 -       nornir -     INFO -        run() - Running task 'netmiko_send_command' with num_workers: 4
2018-10-15 15:35:32,224 -       nornir -     INFO -        run() - Running task 'netmiko_send_command' with num_workers: 4
2018-10-15 15:35:32,225 -       nornir -    DEBUG -        run() - {'command_string': 'show version', 'use_textfsm': True}
2018-10-15 15:35:32,225 -       nornir -    DEBUG -        run() - {'command_string': 'show version', 'use_textfsm': True}
2018-10-15 15:35:32,233 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: netmiko_send_command: running task
2018-10-15 15:35:32,233 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: netmiko_send_command: running task
2018-10-15 15:37:12,330 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 782, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 338, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python3.6/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 338, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 21, in netmiko_send_command
    net_connect = task.host.get_connection("netmiko")
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/inventory.py", line 292, in get_connection
    configuration=config,
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/inventory.py", line 346, in open_connection
    else self.nornir.config,
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/connections/netmiko.py", line 50, in open
    self.connection = ConnectHandler(**parameters)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 270, in __init__
    self.establish_connection()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 787, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_nxos 1.1.1.1:22

2018-10-15 15:37:12,330 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 782, in establish_connection
    self.remote_conn_pre.connect(**ssh_connect_params)
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 338, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python3.6/dist-packages/paramiko/util.py", line 279, in retry_on_signal
    return function()
  File "/usr/local/lib/python3.6/dist-packages/paramiko/client.py", line 338, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/networking/netmiko_send_command.py", line 21, in netmiko_send_command
    net_connect = task.host.get_connection("netmiko")
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/inventory.py", line 292, in get_connection
    configuration=config,
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/inventory.py", line 346, in open_connection
    else self.nornir.config,
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/connections/netmiko.py", line 50, in open
    self.connection = ConnectHandler(**parameters)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/ssh_dispatcher.py", line 218, in ConnectHandler
    return ConnectionClass(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 270, in __init__
    self.establish_connection()
  File "/usr/local/lib/python3.6/dist-packages/netmiko/base_connection.py", line 787, in establish_connection
    raise NetMikoTimeoutException(msg)
netmiko.ssh_exception.NetMikoTimeoutException: Connection to device timed-out: cisco_nxos 1.1.1.1:22

2018-10-15 15:38:22,910 -       nornir -     INFO -        run() - Running task 'dc_access_template' with num_workers: 100
2018-10-15 15:38:22,910 -       nornir -     INFO -        run() - Running task 'dc_access_template' with num_workers: 100
2018-10-15 15:38:22,910 -       nornir -    DEBUG -        run() - {'inventory': <nornir.core.inventory.Inventory object at 0x7f9986018ba8>}
2018-10-15 15:38:22,910 -       nornir -    DEBUG -        run() - {'inventory': <nornir.core.inventory.Inventory object at 0x7f9986018ba8>}
2018-10-15 15:38:22,931 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: dc_access_template: running task
2018-10-15 15:38:22,931 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: dc_access_template: running task
2018-10-15 15:38:22,932 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
TypeError: dc_access_template() missing 1 required positional argument: 'tenant'

2018-10-15 15:38:22,932 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
TypeError: dc_access_template() missing 1 required positional argument: 'tenant'

2018-10-15 15:38:22,932 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: dc_access_template: running task
2018-10-15 15:38:22,932 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: dc_access_template: running task
2018-10-15 15:38:22,932 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_02: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
TypeError: dc_access_template() missing 1 required positional argument: 'tenant'

2018-10-15 15:38:22,932 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_02: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
TypeError: dc_access_template() missing 1 required positional argument: 'tenant'

2018-10-15 15:39:31,918 -       nornir -     INFO -        run() - Running task 'dc_access_template' with num_workers: 100
2018-10-15 15:39:31,918 -       nornir -     INFO -        run() - Running task 'dc_access_template' with num_workers: 100
2018-10-15 15:39:31,919 -       nornir -    DEBUG -        run() - {'inventory': <nornir.core.inventory.Inventory object at 0x7f07aa155b70>}
2018-10-15 15:39:31,919 -       nornir -    DEBUG -        run() - {'inventory': <nornir.core.inventory.Inventory object at 0x7f07aa155b70>}
2018-10-15 15:39:31,942 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: dc_access_template: running task
2018-10-15 15:39:31,942 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: dc_access_template: running task
2018-10-15 15:39:31,943 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
TypeError: dc_access_template() missing 1 required positional argument: 'tenant'

2018-10-15 15:39:31,943 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
TypeError: dc_access_template() missing 1 required positional argument: 'tenant'

2018-10-15 15:39:31,943 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: dc_access_template: running task
2018-10-15 15:39:31,943 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: dc_access_template: running task
2018-10-15 15:39:31,944 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_02: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
TypeError: dc_access_template() missing 1 required positional argument: 'tenant'

2018-10-15 15:39:31,944 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_02: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
TypeError: dc_access_template() missing 1 required positional argument: 'tenant'

2018-10-15 15:41:07,150 -       nornir -     INFO -        run() - Running task 'dc_access_template' with num_workers: 100
2018-10-15 15:41:07,150 -       nornir -     INFO -        run() - Running task 'dc_access_template' with num_workers: 100
2018-10-15 15:41:07,151 -       nornir -    DEBUG -        run() - {'inventory': <nornir.core.inventory.Inventory object at 0x7fbd719c0c18>, 'tenant': 'ipam'}
2018-10-15 15:41:07,151 -       nornir -    DEBUG -        run() - {'inventory': <nornir.core.inventory.Inventory object at 0x7fbd719c0c18>, 'tenant': 'ipam'}
2018-10-15 15:41:07,172 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: dc_access_template: running task
2018-10-15 15:41:07,172 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: dc_access_template: running task
2018-10-15 15:41:07,174 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: dc_access_template: running task
2018-10-15 15:41:07,174 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: dc_access_template: running task
2018-10-15 15:41:07,644 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: Base Configuration: running task
2018-10-15 15:41:07,644 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: Base Configuration: running task
2018-10-15 15:41:07,651 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/text/template_file.py", line 36, in template_file
    **merged
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/helpers/jinja_helper.py", line 10, in render_from_file
    template = env.get_template(template)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: access.j2

2018-10-15 15:41:07,651 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/text/template_file.py", line 36, in template_file
    **merged
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/helpers/jinja_helper.py", line 10, in render_from_file
    template = env.get_template(template)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: access.j2

2018-10-15 15:41:07,652 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "config_generator.py", line 45, in dc_access_template
    path=f"templates/cisco")
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 110, in run
    raise NornirSubTaskError(task=task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Base Configuration (failed)


2018-10-15 15:41:07,652 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_01: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "config_generator.py", line 45, in dc_access_template
    path=f"templates/cisco")
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 110, in run
    raise NornirSubTaskError(task=task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Base Configuration (failed)


2018-10-15 15:41:07,656 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: Base Configuration: running task
2018-10-15 15:41:07,656 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: Base Configuration: running task
2018-10-15 15:41:07,657 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_02: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/text/template_file.py", line 36, in template_file
    **merged
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/helpers/jinja_helper.py", line 10, in render_from_file
    template = env.get_template(template)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: access.j2

2018-10-15 15:41:07,657 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_02: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "/usr/local/lib/python3.6/dist-packages/nornir/plugins/tasks/text/template_file.py", line 36, in template_file
    **merged
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/helpers/jinja_helper.py", line 10, in render_from_file
    template = env.get_template(template)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/dist-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python3.6/dist-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: access.j2

2018-10-15 15:41:07,657 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_02: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "config_generator.py", line 45, in dc_access_template
    path=f"templates/cisco")
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 110, in run
    raise NornirSubTaskError(task=task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Base Configuration (failed)


2018-10-15 15:41:07,657 -       nornir -    ERROR -      start() - MV1_N5K_DC_ACC_02: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 63, in start
    r = self.task(self, **self.params)
  File "config_generator.py", line 45, in dc_access_template
    path=f"templates/cisco")
  File "/usr/local/lib/python3.6/dist-packages/nornir/core/task.py", line 110, in run
    raise NornirSubTaskError(task=task, result=r)
nornir.core.exceptions.NornirSubTaskError: Subtask: Base Configuration (failed)


2018-10-15 15:50:57,487 -       nornir -     INFO -        run() - Running task 'dc_access_template' with num_workers: 100
2018-10-15 15:50:57,487 -       nornir -     INFO -        run() - Running task 'dc_access_template' with num_workers: 100
2018-10-15 15:50:57,487 -       nornir -    DEBUG -        run() - {'inventory': <nornir.core.inventory.Inventory object at 0x7f97795efba8>, 'tenant': 'ipam'}
2018-10-15 15:50:57,487 -       nornir -    DEBUG -        run() - {'inventory': <nornir.core.inventory.Inventory object at 0x7f97795efba8>, 'tenant': 'ipam'}
2018-10-15 15:50:57,508 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: dc_access_template: running task
2018-10-15 15:50:57,508 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: dc_access_template: running task
2018-10-15 15:50:57,510 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: dc_access_template: running task
2018-10-15 15:50:57,510 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: dc_access_template: running task
2018-10-15 15:50:57,755 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: Base Configuration: running task
2018-10-15 15:50:57,755 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_01: Base Configuration: running task
2018-10-15 15:50:57,788 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: Base Configuration: running task
2018-10-15 15:50:57,788 -       nornir -     INFO -      start() - MV1_N5K_DC_ACC_02: Base Configuration: running task
